import { env } from "./env";

export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface ChatOptions {
  model?: string;
  temperature?: number;
  maxTokens?: number;
  // If true we stream tokens back as an async iterable.
  stream?: boolean;
  // Abort the upstream request when this fires.
  signal?: AbortSignal;
}

/**
 * MiniMax chat completion. The platform exposes an OpenAI-compatible
 * /v1/text/chatcompletion_v2 endpoint — we post with fetch and handle both
 * buffered and SSE streaming responses.
 *
 * When MINIMAX_API_KEY is absent we fall back to a deterministic local mock
 * so the app is usable end-to-end without credentials.
 */
export async function minimaxChat(
  messages: ChatMessage[],
  opts: ChatOptions = {},
): Promise<string> {
  if (!env.minimax.apiKey) {
    return mockAnswer(messages);
  }

  const res = await fetch(
    `${env.minimax.baseUrl}/text/chatcompletion_v2`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.minimax.apiKey}`,
      },
      signal: opts.signal,
      body: JSON.stringify({
        model: opts.model ?? env.minimax.model,
        messages,
        temperature: opts.temperature ?? 0.3,
        max_tokens: opts.maxTokens ?? 1024,
        stream: false,
      }),
    },
  );

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`MiniMax error ${res.status}: ${text}`);
  }

  const json = (await res.json()) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  return json.choices?.[0]?.message?.content ?? "";
}

/**
 * Streaming variant. Yields incremental text deltas. Falls back to streaming
 * the mock answer character-wise when no API key is configured.
 */
export async function* minimaxStream(
  messages: ChatMessage[],
  opts: ChatOptions = {},
): AsyncGenerator<string, void, void> {
  if (!env.minimax.apiKey) {
    const full = mockAnswer(messages);
    // Emit in small chunks so the UI can render streaming.
    const chunks = full.match(/.{1,18}/gs) ?? [full];
    for (const c of chunks) {
      await new Promise((r) => setTimeout(r, 20));
      yield c;
    }
    return;
  }

  const res = await fetch(
    `${env.minimax.baseUrl}/text/chatcompletion_v2`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${env.minimax.apiKey}`,
      },
      signal: opts.signal,
      body: JSON.stringify({
        model: opts.model ?? env.minimax.model,
        messages,
        temperature: opts.temperature ?? 0.3,
        max_tokens: opts.maxTokens ?? 1024,
        stream: true,
      }),
    },
  );

  if (!res.ok || !res.body) {
    const text = res.body ? await res.text() : "";
    throw new Error(`MiniMax stream error ${res.status}: ${text}`);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buf = "";
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    buf += decoder.decode(value, { stream: true });
    const lines = buf.split("\n");
    buf = lines.pop() ?? "";
    for (const raw of lines) {
      const line = raw.trim();
      if (!line.startsWith("data:")) continue;
      const payload = line.slice(5).trim();
      if (payload === "[DONE]") return;
      try {
        const obj = JSON.parse(payload) as {
          choices?: Array<{ delta?: { content?: string } }>;
        };
        const delta = obj.choices?.[0]?.delta?.content;
        if (delta) yield delta;
      } catch {
        // MiniMax occasionally emits keepalive comments — ignore.
      }
    }
  }
}

/**
 * Offline fallback. Produces a plausible, citation-shaped answer so the full
 * pipeline (search -> rank -> synthesize -> cite) can be exercised without
 * any outbound API calls.
 */
function mockAnswer(messages: ChatMessage[]): string {
  const last = [...messages].reverse().find((m) => m.role === "user");
  const q = last?.content?.slice(0, 240) ?? "your question";
  return [
    `Here's a synthesized answer for: **${q}**.`,
    "",
    "Scout pulled the most relevant sources and ranked them by a hybrid of keyword overlap, semantic similarity, and freshness [1][2]. The synthesis layer then extracted the load-bearing claims and cross-referenced them against the evidence pack before writing the response [3].",
    "",
    "In production this text is generated by MiniMax. Set `MINIMAX_API_KEY` in `.env.local` to switch from the local mock to the live model.",
  ].join("\n");
}
